version: 1
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
loggers:
  analysis_pipeline:
    handlers: [console]
    level: INFO
    propagate: false
root:
  level: INFO
  handlers: [console]
